=== LO-RAN/codeQualityPortal/Src/ToolBox/src/resources/method.dtd
<!--
    Typical usage:

    <?xml version="1.0"?>

    <!DOCTYPE METHOD SYSTEM "method.dtd">

    <METHOD>
    ...
    </METHOD>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT CRIT EMPTY>
<!ATTLIST CRIT
    weight CDATA #IMPLIED
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT CRITDEF (FORMULA|AGGREG)*>
<!ATTLIST CRITDEF
    id CDATA #IMPLIED
    telt CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT FACT (CRIT)*>
<!ATTLIST FACT
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT FORMULA (OP|VAL)*>
<!ATTLIST FORMULA
    value CDATA #IMPLIED
  >
<!--- aggregation -->
<!ELEMENT AGGREG (PARAM)*>
<!ATTLIST AGGREG
    id CDATA #IMPLIED
    telt CDATA #IMPLIED
  >
<!--- paramÃ¨tre d'aggregation -->
<!ELEMENT PARAM EMPTY>
<!ATTLIST PARAM
    id CDATA #IMPLIED
    value CDATA #IMPLIED
    type CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT METHOD (USAGE)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT OP (OP|VAR|VAL)*>
<!ATTLIST OP
    type CDATA #IMPLIED
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT USAGE (CRITDEF|FACT)*>
<!ATTLIST USAGE
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT VAL EMPTY>
<!ATTLIST VAL
    value CDATA #IMPLIED
    type CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT VAR EMPTY>
<!ATTLIST VAR
    type CDATA #IMPLIED
    id CDATA #IMPLIED
  >

=== LO-RAN/codeQualityPortal/Src/ToolBox/src/resources/method-standard-java.modified.xml
<!DOCTYPE METHOD SYSTEM "method.dtd">

<METHOD>

    <USAGE id="STANDARD-JAVA">

        <CRITDEF id="AVOIDSTARIMPORTCHECK" telt="CLS">
            <AGGREG id="AVG" telt="ALL" />
            <FORMULA value="1">
                <OP id="gt" type="BOOLEAN">
                    <VAR id="AVOIDSTARIMPORTCHECK" type="NUMERIC"/>
                    <VAL value="0" type="NUMERIC"/>
                </OP>
            </FORMULA>
            <FORMULA value="4">
                <VAL value="true" type="BOOLEAN"/>
            </FORMULA>
        </CRITDEF>

        <CRITDEF id="HIDDENFIELDCHECK" telt="CLS">
            <AGGREG id="AVG" telt="ALL" />
            <FORMULA value="1">
                <OP id="gt" type="BOOLEAN">
                    <VAR id="HIDDENFIELDCHECK" type="NUMERIC"/>
                    <VAL value="0" type="NUMERIC"/>
                </OP>
            </FORMULA>
            <FORMULA value="4">
                <VAL value="true" type="BOOLEAN"/>
            </FORMULA>
        </CRITDEF>

        <CRITDEF id="MAGICNUMBERCHECK" telt="CLS">
            <AGGREG id="AVG" telt="ALL" />
            <FORMULA value="1">
                <OP id="gt" type="BOOLEAN">
                    <VAR id="MAGICNUMBERCHECK" type="NUMERIC"/>
                    <VAL value="0" type="NUMERIC"/>
                </OP>
            </FORMULA>
            <FORMULA value="4">
                <VAL value="true" type="BOOLEAN"/>
            </FORMULA>
        </CRITDEF>

        <CRITDEF id="JAVADOCMISSING" telt="CLS">
            <AGGREG id="AVG" telt="ALL" />
            <FORMULA value="1">
                <OP id="gt" type="BOOLEAN">
                    <VAR id="JAVADOCMETHODCHECK" type="NUMERIC"/>
                    <VAL value="0" type="NUMERIC"/>
                </OP>
            </FORMULA>
            <FORMULA value="1">
                <OP id="gt" type="BOOLEAN">
                    <VAR id="JAVADOCTYPECHECK" type="NUMERIC"/>
                    <VAL value="0" type="NUMERIC"/>
                </OP>
            </FORMULA>
            <FORMULA value="4">
                <VAL value="true" type="BOOLEAN"/>
            </FORMULA>
        </CRITDEF>


    </USAGE>
</METHOD>
